name: ASP.NET core WebApi CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 
    - name: Restore
      run: dotnet restore EffectiveMobile-ASP-RestApi-Test-main.sln

    - name: Build
      run: dotnet build EffectiveMobile-ASP-RestApi-Test-main.sln 

    - name: Run tests
      run: dotnet test EffectiveMobile-ASP-RestApi-Test-main.sln
